// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package game

import "strconv"

const _ActionType_name = "PassPlayActivateAttackBlockChooseTargetAndManaDecideOnChoiceDeclineChoiceEntersTheBattlefieldEffectMakeChoicePassPriorityUseForMana"

var _ActionType_index = [...]uint8{0, 4, 8, 16, 22, 27, 46, 60, 73, 99, 109, 121, 131}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
