// Code generated by "stringer -type=AttackStatus"; DO NOT EDIT.

package game

import "strconv"

const _AttackStatus_name = "NotInCombatAttackingBlockedBlockingUnblocked"

var _AttackStatus_index = [...]uint8{0, 11, 20, 27, 35, 44}

func (i AttackStatus) String() string {
	if i < 0 || i >= AttackStatus(len(_AttackStatus_index)-1) {
		return "AttackStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttackStatus_name[_AttackStatus_index[i]:_AttackStatus_index[i+1]]
}
