// Code generated by "stringer -type=CardName"; DO NOT EDIT.

package game

import "strconv"

const _CardName_name = "NoCardBurningTreeEmissaryCounterspellDazeEldraziSpawnTokenElephantGuideElephantTokenFaerieMiscreantForestGrizzlyBearsGushHungerOfTheHowlpackIslandMutagenicGrowthNestInvaderNettleSentinelNinjaOfTheDeepHoursPonderPreordainQuirionRangerRancorSilhanaLedgewalkerSkarrganPitskulkSnapSpellstutterSpriteVaultSkirgeVinesOfVastwood"

var _CardName_index = [...]uint16{0, 6, 25, 37, 41, 58, 71, 84, 99, 105, 117, 121, 140, 146, 161, 172, 186, 205, 211, 220, 233, 239, 257, 273, 277, 295, 306, 321}

func (i CardName) String() string {
	if i < 0 || i >= CardName(len(_CardName_index)-1) {
		return "CardName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardName_name[_CardName_index[i]:_CardName_index[i+1]]
}
