// Code generated by "stringer -type=MTGSubtype"; DO NOT EDIT.

package game

import "strconv"

const _MTGSubtype_name = "BasicForestBasicIsland"

var _MTGSubtype_index = [...]uint8{0, 11, 22}

func (i MTGSubtype) String() string {
	if i < 0 || i >= MTGSubtype(len(_MTGSubtype_index)-1) {
		return "MTGSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MTGSubtype_name[_MTGSubtype_index[i]:_MTGSubtype_index[i+1]]
}
