// Code generated by "stringer -type=MTGType"; DO NOT EDIT.

package game

import "strconv"

const _MTGType_name = "CreatureLand"

var _MTGType_index = [...]uint8{0, 8, 12}

func (i MTGType) String() string {
	if i < 0 || i >= MTGType(len(_MTGType_index)-1) {
		return "MTGType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MTGType_name[_MTGType_index[i]:_MTGType_index[i+1]]
}
