// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package game

import "strconv"

const _Phase_name = "UntapStepUpkeepDrawMain1DeclareAttackersDeclareBlockersCombatDamageMain2"

var _Phase_index = [...]uint8{0, 9, 15, 19, 24, 40, 55, 67, 72}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
