// Code generated by "stringer -type=PlayerSelector"; DO NOT EDIT.

package game

import "strconv"

const _PlayerSelector_name = "SamePlayerOpposingPlayer"

var _PlayerSelector_index = [...]uint8{0, 10, 24}

func (i PlayerSelector) String() string {
	if i < 0 || i >= PlayerSelector(len(_PlayerSelector_index)-1) {
		return "PlayerSelector(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerSelector_name[_PlayerSelector_index[i]:_PlayerSelector_index[i+1]]
}
