// Code generated by "stringer -type=PlayerTargetType"; DO NOT EDIT.

package game

import "strconv"

const _PlayerTargetType_name = "SamePlayerOpposingPlayer"

var _PlayerTargetType_index = [...]uint8{0, 10, 24}

func (i PlayerTargetType) String() string {
	if i < 0 || i >= PlayerTargetType(len(_PlayerTargetType_index)-1) {
		return "PlayerTargetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerTargetType_name[_PlayerTargetType_index[i]:_PlayerTargetType_index[i+1]]
}
