// Code generated by "stringer -type=Subtype"; DO NOT EDIT.

package game

import "strconv"

const _Subtype_name = "NoSubtypeLandForestLandIslandLandMountainLandPlainsLandSwampFaerie"

var _Subtype_index = [...]uint8{0, 9, 19, 29, 41, 51, 60, 66}

func (i Subtype) String() string {
	if i < 0 || i >= Subtype(len(_Subtype_index)-1) {
		return "Subtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subtype_name[_Subtype_index[i]:_Subtype_index[i+1]]
}
