// Code generated by "stringer -type=Supertype"; DO NOT EDIT.

package game

import "strconv"

const _Supertype_name = "BasicLegendarySnowWorld"

var _Supertype_index = [...]uint8{0, 5, 14, 18, 23}

func (i Supertype) String() string {
	if i < 0 || i >= Supertype(len(_Supertype_index)-1) {
		return "Supertype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Supertype_name[_Supertype_index[i]:_Supertype_index[i+1]]
}
